# Generated by Django 2.0.7 on 2020-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='Enterprise',
            field=models.TextField(default='no'),
        ),
    ]
