# Generated by Django 3.0.2 on 2020-01-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterForm', '0003_auto_20200111_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='Enterprise',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='Residential',
        ),
    ]
