# Generated by Django 3.0.2 on 2020-01-17 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterForm', '0005_remove_registerform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
