# Generated by Django 3.0.2 on 2020-01-23 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterForm', '0006_registerform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='phoneNumber',
            field=models.TextField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
