# Generated by Django 3.0.2 on 2020-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterForm', '0007_auto_20200123_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='phoneNumber',
            field=models.TextField(),
        ),
    ]
