# Generated by Django 3.0.2 on 2020-01-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='residential',
        ),
    ]
